
// CONSTANTS Card
export const LIEU = "Lieu :"
export const LIEUX = "Lieu"
export const HEURE = "Heure"
export const DUREE = "Durée :"
export const DUREES = "Durée"
export const DEBUT = "Début"
export const DATE  = "Date"
export const PRIX  = "Prix"
export const PROGRAMDETAILS  = "detail programme"
export const SEMAINES  = "Semaine(s)"
//And CONSTANTS Card

// CONSTANTS event
export const A = "à"
export const EVENEMENT  = "LES EVENEMENTS"
export const LINK  = "Plus"
//And CONSTANTS event

// CONSTANTS Navbar
export const PROGRAMME = "programmes"
export const EVENEMENTS  = "EVENEMENTS"
export const NOUVEAU  = "ACTUALITÉS"
export const INSTRUCTEURS  = " Devenir Instructeur "
//And CONSTANTS Navbar

// CONSTANTS centre d'aide
export const CONTACTS = "CONTACTER NOUS"
export const INS_COACHING  = "INSCRIPTION COACHING"
export const COACHING  = "Laissez-nous vous aider à déterminer si un programme vous convient. Nos coachs d'inscription sont formés pour vous guider dans l'évaluation de votre état de préparation et de votre aptitude, de vous préparer à postuler et de vous inscrire avec succès à un programme de certificat."
export const OBTENIR_AIDE  = "OBTENIR DE L'AIDE"
export const TEL  = "Téléphone :"
export const NUMBER  = "+224 629-57-97-48"
export const SERVICES_INSCRIT  = "SERVICES D'INSCRIPTION"
export const DETAIT_SERVICES_INSCRIT  = "Appelez-nous ou visitez-nous pour vous inscrire et payer une formation. Nous sommes également là pour répondre à vos questions sur l'inscription et le paiement."
export const MAIL1  = "info@plaguifor.com"
export const MAIL  = "Couriel :"
export const QUESTIONS_GÉNÉRALES  = "QUESTIONS GÉNÉRALES"
export const DETAIL_QUESTIONS_GÉNÉRALES  = "Des questions sur votre programme ou un autre problème? Nous sommes là pour vous aider."
export const MAIL2  = "info@plaguifor.com"
export const PLA_FORM="PLAGUIFOR"
export const PSWORD_OUBLIE="Mot de passe oublié"
//And CONSTANTS centre d'aide

// CONSTANTS Programme
export const PREUNIV = "pré-universitaires"
export const PROFESSIONNELLE  = "professionnelle"
export const NONPROFESSIONNELLE  = "Autres"
//And CONSTANTS Programme

//Evens
export const Even="Evénement"
export const features="Actualités"

//Even

// CONSTANTS HommePage
export const PARTENARIAT_S  = "Partenariat avec nous"
export const PROPOSITION  = "Proposer nous une formation"
export const A_PROPOS  = "À Propos de nous"
//And CONSTANTS HommePage

// CONSTANTS Partenariat
export const INFOS_PARTENARIAT_S  = "Pour en savoir plus sur le partenariat avec nous ou pour devenir membre du conseil consultatif,"
export const NOUS_CONTACTER = "CONTACTEZ-NOUS"
//And CONSTANTS Partenariat

// CONSTANTS aide
export const AIDE = "CENTRE D'AIDE"
export const P_PROGRAM = "Postuler à un programme"
//And CONSTANTS aide

export const UN_INNOVANT = "Un innovant système de formation pour lutter contre le chômage des jeunes. L’Enseignement de qualité pour toute personne désireuse de continuer ses Etudes Supérieures malgré ses occupations professionnelles.Un  renforcement des niveaux et des capacités des élèves et enseignants de la pré-universitaire"
export const VOUS_DESIRIEZ = "Vous désirez ou souhaitez entretenir, mettre à jour vos compétences, renforcer vos capacités opérationnelles et professionnelles et/ou vous inscrire dans la dynamique de la modernisation du monde professionnel et de votre profession actuelle et à venir; vous êtes Entrepreneur ou désirant entreprendre; vous êtes des artistes ou autres créateurs ambitionnant se développer alors, PLAGUIFOR est votre solution pour la mise en œuvre de votre noble ambition."
export const HEADER = "Continuer à apprendre et de parfaire vos connaissances dans les grandes institutions et d’Enseignement Supérieur. \nGarantir la formation continue malgré vos charges et temps de travail et, malgré votre lieu de résidence. \nRéaliser vos rêves de Développement personnel et de Réussite globale et multiforme ;"

export const FOOTER_SUBSCRIPTION ="En soumettant mes informations, je consens à être contacté par e-mail. "

export const NOUS_SOMMES = "Nous sommes une plateforme multidisciplinaire et multisectorielle. Nous avons pour VOCATION de participer et de nous impliquer dans le Développement Durable de nos Nations et des potentiels de nos concitoyens."
export const DE_CE_FAIT = "De ce fait et pour y parvenir qualitativement et de façon durable, nous offrons les solutions et l’expertise nécessaire au Développement individuel et collectif des personnes dans leurs activités professionnelles et/ou de leur Entreprise ou initiative. Nos domaines d’action sont multiples, variés et diversifiés et, qui sont entre autres :"
export const ENSEIGGNEMENT_DE_QUALITE = "L’Enseignement de qualité pour toute personne désireuse de continuer ses Etudes Supérieures malgré ses occupations professionnelles ;"
export const RENFORCEMENT_DES_NIVEAUX = "Renforcement des niveaux et des capacités des élèves et enseignants de la pré-universitaire ;"
export const LA_PROMOTION = "La promotion des personnes qualifiées et de leurs activités ;" 
export const IDENTIFICATION = "Identification et recrutement des compétences pour tiers ; "
export const LA_FORMATION = "La formation des formateurs et des adultes;"
export const RENFORCEMET_DES_CAPACITES = "Renforcement des capacités institutionnelles, des Administrateurs, des Groupement d’Intérêt Economique et autres regroupements corporatifs ; "
export const AVEC_UN_RESEAU = "Avec un réseau performant d’Universités et de Grandes Ecoles, des formateurs et des personnes ressources hautement qualifiés, une organisation savamment performante, PLAGUIFOR entend éliminer les barrières afin que, les personnes de tous types puissent accéder à des opportunités de qualité qui correspondent à leur Vie. Nous sommes conscients de la nécessité de renforcer les capacités et compétences pour être en mesure de répondre et de satisfaire aux besoins en constant changement dans un monde qui évolue à grande enjambée." 
export const NOUS_SOMMES_EGALEMENT = "Nous sommes également convaincus que la quête et l’acquisition du savoir rendent la vie plus significative. C’est pourquoi, nous sommes dans une phase constante et permanente de recherche et de développement, expérimentant de nouveaux sujets ou produits que gardent à l’esprit le nouvel apprenant traditionnel et non traditionnel." 
export const QUE_VOUS_POURSIVIEZ = "Que vous poursuiviez un niveau d’étude supérieur, que vous soyez dans le préscolaire comme élève ou Enseignant, que vous soyez des salariés en activité ou pas, que vous soyez une structure à caractère associatif, communautaire ou corporatif, que vous soyez des artistes,……, PLAGUIFOR est incontestablement cette plateforme qui a  le Pouvoir et la Capacité de vous développer durablement et, faire de votre Réussite une REALITE." 
export const VALIDE="VALIDER"
export const OFFRE="Offre d'Emploi"
export const ADRESSE_PLAGUI="© 2021 KIMBELI SA | Yembeya, Conakry | Titre IX | "
export const P_KIMBELI="Présenté par le groupe KIMBELI"
export const ON_EST_LA="On est là pour vous"
export const Q_GENERAL="QUESTIONS GENERAL"
export const DETAIL_Q_GENERAL="Vous avez une petite question? Nous sommes là pour vous aider!"
export const NOUS_SOMME_LA="NOUS SOMMES ICI POUR VOUS"
export const DETAIL_NOUS_SOMME_LA="NOUS SOMMES ICI POUR VOUS"
export const DETAIL_ON_EST_LA="Nos coachs d'inscription sont là pour vous aider à évaluer votre état de préparation et votre aptitude pour un programme de certificat, à vous préparer à postuler et à vous inscrire avec succès. Envoyez simplement ce formulaire afin que nous sachions ce qui vous intéresse et nous vous contacterons."
export const CHAMP="Tous les champs sont obligatoires"
export const INFO_FORM="les informations de la formation"
export const NOS_CATEGORIE="Nos catégories"
export const S_CATEGORIE="---sélectionner une catégorie---"
export const DEGRE="Degré"
export const S_DEGRE="---sélectionner le degré---"
export const NOM_F="le nom de la formation"
export const VOS_INFOS="Vos informations"
export const BIENVENUE="BIENVENUE A PLAGUIFOR"
export const DISPO="Disponible du"
export const LUNDI="LUNDI"
export const MARDI="MARDI"
export const MERCREDI="MERCREDI"
export const JEUDI="JEUDI"
export const VENDREDI="VENDREDI"
export const SAMEDI="SAMEDI"
export const DIMANCHE="DIMANCHE"

export const INFORMATIQUE="Informatique"
export const RESSOURCE="Ressource Humaine"
export const SANTE="Santé"
export const T_PUBLIC="Travaux publics"
export const MARKETEENG="Marketing"
export const HOTELERIE="Hôtélerie et tourisme"
// constant text Dashborad
export const PARAMETRE="Paramètres"
export const TABLEAU_BORD="Tableau de bord"
export const GESTION="La gestion"
export const L_FORMATIONS="Liste de formations"
export const C_FORMATION="Créer une formation"
export const COMPTE="Compte"
export const PROFIL="Pofil"
export const RAPPORT="Rapport"
export const B_AIDE="Besoin d'aide?"
export const DETAIL_B_AIDE="info@plaguifor.com"
export const DETAIL_B_AIDE1="+224 629-57-97-48"
export const CONS_DOCUMENT="Compte"
export const C_PASSWRD="Changer le mot de passe"
export const E_MODIFIER="Enregistrer les modifications"
export const V_CATEGORIE="Veuillez selectionner une catégorie"
export const PRECEDENT="Précedent"
export const SUIVANT="Suivant"
export const CRE_ASS_PROCESSUS="Créer un assistant et un processus"
export const S_OPTION="Veuillez sélectionner une option"
export const DETAIL_S_OPTION="Veuillez sélectionner une option"
export const S_REMPLIR="Veuillez sélectionner remplir"
export const COMPLETE="COMPLÉTER"
export const PROJET="Projet"
export const DETAIL_S_REMPLIR="Développeurs et entrepreneurs de micro-ondes avant que cela ne devienne infructueux. Fringilla velit sit amet euismod Quisque aliquam."
// and constant Dashboard

export const DETAIL_BIENV1="Vous envisagez plusieurs certificats ou heures de début? Soumettez le formulaire pour une seule option, et nous serons heureux d'en parler plus lors du suivi."
export const DETAIL_BIENV2="Vous ne voyez pas le programme que vous recherchez? Appelez-nous au lieu de soumettre le formulaire."
export const RENCONTRE="RENCONTREZ LES SERVICES D'INSCRIPTION"
export const DEATAIL_RENCONTRE="Renseignez-vous sur l'experience d'un étudiant travaillant avec un coach d'inscription et découvrez comment nous pourrions vous aider."
export const COURS="Cours"
export const CERTIFICAT="Certificat"
export const TIME="08H 00 A 17H 00"
export const DOMMAINE="Dommaine d'Étude"
export const L_INTERET="LIEU D'INTÉRET"
export const SVP_OPTION="Veuillez choisir une option"
export const PROPOS_PROGRAMM="À PROPOS DE CE PROGRAMME"
export const APPRENDRE="CE QUE VOUS APPRENDREZ"
export const CONÇU="CONÇU POUR"
export const APERÇU="APERÇU DU PROGRAMME"
export const COUT="PRIX :"
export const START_DATE="Date démmarage :"
export const NEXT_DATE="PROCHAINE DATE DE DÉBUT:"

export const CONFIDENTIALITE="Politique de confidentialité"
export const DERNIER_MJOUR="Dernière mise à jour: 25 avril 2021"
export const DETAI_DERNIER_MJOUR="Cette politique de confidentialité décrit nos politiques et procédures sur le collecte, utilisation et divulgation de vos informations lorsque vous utilisez le Service et vous informe de vos droits à la vie privée et de la manière dont la loi vous protège. Nous utilisons vos données personnelles pour fournir et améliorer le Un service. En utilisant le Service, vous acceptez la collecte et l'utilisation d'informations conformément à cette politique de confidentialité. Cette confidentialité La politique a été créée à l'aide de la politique de confidentialité Générateur."
export const INTER="Interpretation"
export const DEFINI="définitions"
export const AUX_FIN="Aux fins de cette politique de confidentialité:"
export const ET="et"
export const DETAI_DEFINI="Les mots dont la lettre initiale est en majuscule ont des significations défini dans les conditions suivantes. Les définitions suivantes ont la même signification, qu'ils apparaissent ou non dans singulier ou au pluriel."
export const COMPTE_DETAIL="créé pour que vous puissiez accéder à notre service ou à certaines parties de notre service."
export const COMPAGNIE="Compagnie"
export const COMPAGNIE_DETAIL="(référé comme «la société», «nous», «nous» ou «notre» dans ce Accord) fait référence à PLAGUIFOR."
export const COKIE="Cookies"
export const COKIE_DETAIL="sont petits fichiers placés sur votre ordinateur, appareil mobile ou tout autre appareil par un site Web, contenant les détails de votre l'historique de navigation sur ce site Web parmi ses nombreuses utilisations."
export const CUNTRY="Pays"
export const CUNTRY_DETAIL="se réfère à: Guinée."
export const APPAREIL="Appareil"
export const APPAREIL_DETAIL="signifie tout appareil pouvant accéder au Service tel qu'un ordinateur, un téléphone portable ou tablette numérique."
export const D_PERSONNEL="Données personnelles"
export const D_PERSONNEL_DETAIL="Données personnelles"
export const F_SERVICE="Fournisseur de services"
export const F_SERVICE_DETAIL="désigne toute personne physique ou morale qui traite les données sur au nom de la société. Il fait référence à des sociétés tierces ou les personnes employées par la Société pour faciliter le Service, pour fournir le Service au nom de la Société, pour exécuter services liés au Service ou pour aider la Société à analyser la façon dont le service est utilisé."
export const T_PERSONNE="Tierce personne"
export const T_PERSONNE_DETAIL="Le service de médias sociaux fait référence à tout site Web ou tout réseau social site Web du réseau via lequel un utilisateur peut se connecter ou créer un compte pour utiliser le service."
export const D_UTILE=" Données d'utilisation"
export const D_UTILE_DETAIL="fait référence aux données collectées automatiquement, soit générées par l'utilisation du Service ou de l'infrastructure du Service lui-même (par exemple, la durée d'une visite de page)."
export const S_INTERNET="Site Internet"
export const S_INTERNET_DETAIL="fait référence à PLAGUIFOR, accessible depuis https://www.plaguifor.com"
export const T_VEUX="Tu veux"
export const T_VEUX_DETAIL=" personne accédant ou utilisant le Service, ou l'entreprise, ou autre entité juridique au nom de laquelle cette personne est accéder ou utiliser le Service, selon le cas."
export const COLECT_UTILE=" Collecte et utilisation de vos données personnelles"
export const T_DONNEE="Types de données collectées"
export const UTILE_SERVICE="Lors de l'utilisation de notre service, nous pouvons vous demander de nous fournir certains informations personnellement identifiables qui peuvent être utilisées pour contacter ou vous identifier. Les informations personnellement identifiables peuvent inclure, mais sont pas limité à:"
export const ADRESSE_MAIL="Adresse e-mail"
export const PRENOM_NOM="Prénom et nom"
export const DETAIL="Adresse, état, province, code postal, ville"
export const D_COLLECTE="Les données d'utilisation sont collectées automatiquement lors de l'utilisation du service."
export const DONNEE_DETAIL=" Les données d'utilisation peuvent inclure des informations telles que l'Internet de votre appareil Adresse de protocole (par exemple, adresse IP), type de navigateur, version du navigateur, les pages de notre service que vous visitez, l'heure et la date de votre visite, le temps passé sur ces pages, les identifiants uniques de l'appareil et autres données de diagnostic."
export const DONNEE_DETAIL2=" Lorsque vous accédez au service par ou via un appareil mobile, nous pouvons collecter automatiquement certaines informations, y compris, mais sans s'y limiter à, le type d'appareil mobile que vous utilisez, l'identifiant unique de votre appareil mobile, l'adresse IP de votre appareil mobile, votre système d'exploitation mobile, le type de navigateur Internet mobile que vous utilisez, les identifiants uniques de l'appareil et autres données de diagnostic."
export const DONNEE_INFOS=" Nous pouvons également collecter des informations que votre navigateur envoie chaque fois que vous visitez notre service ou lorsque vous accédez au service par ou via un appareil mobile."
export const INFOS_SERVICE=" Informations provenant de services de médias sociaux tiers"
export const SOCIETE_INFOS="La société vous permet de créer un compte et de vous connecter pour utiliser le Service via les services de médias sociaux tiers suivants:"
export const GOOGLE="Google"
export const FACEBOOK="Facebook"
export const TWITTER ="Twitter"
export const DETAIL3=" Si vous décidez de vous inscrire ou de nous accorder l'accès à un Service de médias sociaux tiers, nous pouvons collecter des données personnelles déjà associé à votre service de médias sociaux tiers compte, comme votre nom, votre adresse e-mail, vos activités ou Votre liste de contacts associée à ce compte. Vous pouvez également avoir la possibilité de partager des informations supplémentaires avec la société via le compte de votre service de médias sociaux tiers. Si vous choisissez de fournir ces informations et données personnelles, pendant inscription ou autrement, vous autorisez la société à utilisez, partagez et stockez-le d'une manière compatible avec cette confidentialité Politique"
export const T_COKIE=" Technologies de suivi et cookies"
export const T_COKIE_DETAIL="Nous utilisons des cookies et des technologies de suivi similairesb pour suivre l'activité sur notre service et stocker certaines informations. Technologies de suivi utilisés sont des balises, des balises et des scripts pour collecter et suivre des informations et pour améliorer et analyser notre service. Les technologies que nous utilisons peuvent inclure:"
export const COKIE_NAV=" Cookies ou cookies de navigateur."
export const COKIE_NAV_DETAIL=" Un cookie est un petit fichier placé sur votre appareil. Vous pouvez instruire Votre navigateur pour refuser tous les cookies ou pour indiquer quand un cookie est envoyé. Cependant, si vous n'acceptez pas les cookies, vous pouvez ne pas pouvoir utiliser certaines parties de notre service. Sauf si vous avez ajusté les paramètres de votre navigateur afin qu'il refuse les cookies, notre service peut utiliser des cookies"
export const COKE_FLASH="Cookies Flash."
export const COKE_FLASH_DETAIL="Certaines fonctionnalités de notre service peuvent utiliser des objets stockés localement (ou Flash Cookies) pour collecter et stocker des informations sur votre préférences ou votre activité sur notre service. Les cookies Flash sont non géré par les mêmes paramètres de navigateur que ceux utilisés pour Cookies de navigateur. Pour plus d'informations sur la façon dont vous pouvez supprimer Cookies Flash, veuillez lire Où puis-je modifier les paramètres de désactiver ou supprimer des objets partagés locaux? disponible sur https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_"
export const B_WEB="Balises Web."
export const B_WEB_DETAIL=" Certaines sections de notre service et de nos e-mails peuvent contenir de petits fichiers électroniques connus sous le nom de balises Web (également appelées clear gifs, balises pixel et gifs pixel unique) qui permettent Entreprise, par exemple, pour compter les utilisateurs qui ont visité ces pages ou a ouvert un e-mail et pour un autre site Web associé statistiques (par exemple, enregistrer la popularité d'un certain section et vérification de l'intégrité du système et du serveur)."
export const DETAIL_COKIE=" Les cookies peuvent être des cookies «persistants» ou «de session». Cookies persistants rester sur votre ordinateur personnel ou appareil mobile lorsque vous vous déconnectez, tandis que les cookies de session sont supprimés dès que vous fermez votre site Web le navigateur. En savoir plus sur les cookies: Cookies: que font-ils?."
export const COKIE_UTILE="Nous utilisons à la fois des cookies de session et des cookies persistants aux fins énoncées au dessous de:"
export const COKIE_N=" Cookies nécessaires / essentiels"
export const TYPE_COKIE=" Type: Cookies persistants"
export const ADMINE="  Administré par: nous"
export const OBJECTIF="Objectif: ces cookies sont essentiels pour vous fournir des services disponible sur le site Web et pour vous permettre d'utiliser certains de ses fonctionnalités. Ils aident à authentifier les utilisateurs et à prévenir les fraudes utilisation des comptes utilisateurs. Sans ces cookies, les services que vous ont demandé ne peuvent pas être fournis, et nous utilisons uniquement ces cookies pour vous fournir ces services."
export const P_COKIE=" Politique de cookies / Avis d'acceptation des cookies"
export const O_COKIE=" Objectif: ces cookies identifient si les utilisateurs ont accepté l'utilisation de cookies sur le site Web."
export const COKIE_F=" Cookies de fonctionnalité"
export const ROLE_COKIE="  Objectif: ces cookies nous permettent de nous souvenir des choix que vous faites lorsque Vous utilisez le site Web, par exemple en vous souvenant de vos informations de connexion ou Préférence de langue. Le but de ces cookies est de fournir Vous avec une expérience plus personnelle et pour vous éviter d'avoir à ressaisissez vos préférences chaque fois que vous utilisez le site Web."
export const ROLE_COKIE_DETAIL=" Pour plus d'informations sur les cookies que nous utilisons et vos choix concernant les cookies, veuillez consulter notre politique de cookies ou les cookies section de notre politique de confidentialité."
export const D_UTILIE2="  Utilisation de vos données personnelles"
export const S_UTILE="La Société peut utiliser les données personnelles aux fins suivantes"
export const MAINTENIR=" Pour fournir et maintenir notre service,"
export const MAINTENIR_DETAIL =" y compris pour surveiller l'utilisation de notre service."
export const G_COMPTE= "Pour gérer votre compte: pour gérer votre inscription en tant qu'utilisateur de le service. Les données personnelles que vous fournissez peuvent vous donner accès aux différentes fonctionnalités du Service disponibles à Vous en tant qu'utilisateur enregistré."
export const EX_CONTRAT=" Pour l'exécution d'un contrat:"
export const EX_CONTRAT_DETAIL=" le développement, la conformité et la réalisation de l'achat contrat pour les produits, articles ou services que vous avez achetés ou de tout autre contrat avec Nous via le Service."
export const INFOS_CONTACT=" À Vous contacter par e-mail, appels téléphoniques, SMS ou autre équivalent formes de communication électronique, comme un mobile les notifications push de l'application concernant les mises à jour ou communications informatives liées aux fonctionnalités, produits ou services sous-traités, y compris les mises à jour de sécurité, lorsque cela est nécessaire ou raisonnable pour leur mise en œuvre."
export const FOURNIR="Pour vous fournir"
export const FOURNIR_DETAIL=" avec actualités, offres spéciales et informations générales sur d'autres produits, services et événements que nous proposons similaires à ceux que vous avez déjà acheté ou demandé à moins que vous ont choisi de ne pas recevoir de telles informations."
export const G_DEMANDE=" Pour gérer vos demandes:"
export const A_DEMANDE=" Pour assister et gérer vos demandes."
export const T_ENTREPRISE=" Pour les transferts d'entreprise:"
export const T_ENTREPRISE_DETAIL=" Nous pouvons utiliser vos informations pour évaluer ou mener une fusion, désinvestissement, restructuration, réorganisation, dissolution ou autre vente ou transfert de tout ou partie de nos actifs, que ce soit en tant que une entreprise en exploitation ou dans le cadre d'une faillite, liquidation ou procédure similaire, dans laquelle les données personnelles que nous détenons sur notre Les utilisateurs du service font partie des actifs transférés."
export const AUTRE_FIN="À d'autres fins:"
export const AUTRE_FIN_DETAIL="Nous pouvons utiliser vos informations à d'autres fins, telles que des données analyse, identification des tendances d'utilisation, détermination de la l'efficacité de nos campagnes promotionnelles et pour évaluer et améliorer notre service, nos produits, nos services, notre marketing et votre vivre."
export const P_INFOS="Nous pouvons partager vos informations personnelles dans les situations suivantes:"
export const A_SERVICE=" Avec les fournisseurs de services:"
export const A_SERVICE_DETAIL=" Nous pouvons partager vos informations personnelles avec des fournisseurs de services pour surveiller et analyser l'utilisation de notre service, pour vous contacter."
export const P_ENTREPRISE=" Pour les transferts d'entreprise:"
export const P_ENTREPRISE_DETAIL="  Nous pouvons partager ou transférer vos informations personnelles en relation avec ou pendant les négociations de toute fusion, vente de la société actifs, financement ou acquisition de tout ou partie de nos entreprise à une autre entreprise."
export const A_AFFILE="Avec les affiliés:"
export const A_AFFILE_DETAIL="Nous pouvons partager vos informations avec nos affiliés, auquel cas nous demanderons à ces affiliés d'honorer cette politique de confidentialité. Les affiliés incluent notre société mère et tout autre filiales, partenaires de coentreprise ou autres sociétés que nous contrôle ou qui sont sous contrôle commun avec nous."
export const P_COMMERCIAUX=" Avec des partenaires commerciaux:"
export const P_COMMERCIAUX_DETAIL="Nous pouvons partager vos informations avec nos partenaires commerciaux pour vous offrir certains produits, services ou promotions."
export const AUTRE_USER="Avec d'autres utilisateurs:"
export const AUTRE_USER_DETAIL=" lorsque vous partagez des informations personnelles ou interagissez autrement dans le zones publiques avec d'autres utilisateurs, ces informations peuvent être consultées par tous les utilisateurs et peuvent être diffusés publiquement à l'extérieur. Si vous interagir avec d'autres utilisateurs ou s'inscrire via un tiers Service de médias sociaux, vos contacts sur les réseaux sociaux tiers Le service média peut voir votre nom, votre profil, vos photos et description de votre activité. De même, les autres utilisateurs seront capable de consulter les descriptions de votre activité, de communiquer avec vous et affichez votre profil."
export const CONSENTEMENT="Avec votre consentement:"
export const CONSENTEMENT_DETAIL=" Nous pouvons divulguer vos informations personnelles à toute autre fin avec votre consentement."
export const CONSERVE_DONNEE=" Conservation de vos données personnelles"
export const CONSERVE_DONNEE_DETAIL=" La Société conservera vos données personnelles uniquement aussi longtemps que nécessaire aux fins énoncées dans la présente politique de confidentialité. On le fera conserver et utiliser vos données personnelles dans la mesure nécessaire pour se conformer avec nos obligations légales (par exemple, si nous sommes tenus de vos données pour se conformer aux lois applicables), résoudre les litiges, et appliquer nos accords juridiques et nos politiques."
export const CONSERVE_DONNEE_DETAIL2=" La Société conservera également les données d'utilisation à des fins d'analyse interne fins. Les données d'utilisation sont généralement conservées pendant une période plus courte heure, sauf lorsque ces données sont utilisées pour renforcer la sécurité ou pour améliorer la fonctionnalité de notre service, ou nous sommes légalement obligé de conserver ces données pendant des périodes plus longues."
export const TRANSFERT_DONNEE="Transfert de vos données personnelles"
export const TRANSFERT_DONNEE_DETAIL=" Vos informations, y compris les données personnelles, sont traitées au Les bureaux d'exploitation de la société et dans tout autre endroit où le les parties impliquées dans le traitement sont localisées. Cela signifie que ce les informations peuvent être transférées et conservées sur des ordinateurs situé en dehors de votre état, province, pays ou autre juridiction gouvernementale où les lois sur la protection des données peuvent différer que ceux de votre juridiction."
export const CONSENTEMENT_INFOS=" Votre consentement à cette politique de confidentialité suivi de votre soumission de ces informations représentent votre accord à ce transfert."
export const CONSENTEMENT_INFOS_DETAIL=" La Société prendra toutes les mesures raisonnablement nécessaires pour assurer que vos données sont traitées en toute sécurité et conformément à ce Politique de confidentialité et aucun transfert de vos données personnelles ne prendra place à une organisation ou à un pays à moins qu'il n'y ait contrôles en place, y compris la sécurité de vos données et autres renseignements personnels."
export const DEVULGATION=" Divulgation de vos données personnelles"
export const TRANSACTION=" Transactions commerciales"
export const T_CONTACTER="Te contacter:"
export const TRANSACTION_DETAIL="  Si la Société est impliquée dans une fusion, une acquisition ou une vente d'actifs, Vos données personnelles peuvent être transférées. Nous fournirons un avis avant Vos données personnelles sont transférées et font l'objet d'un autre Politique de confidentialité."
export const ENFORCEMENT="  Law enforcement"
export const ENFORCEMENT_DETAIL="Dans certaines circonstances, la Société peut être tenue de divulguer Vos données personnelles si la loi l'exige ou en réponse à des les demandes des autorités publiques (par exemple, un tribunal ou une agence gouvernementale)."
export const A_EXIGE=" Autres exigences légales"
export const D_SOCIETE="  La Société peut divulguer vos données personnelles de bonne foi qu'une telle action est nécessaire pour:"
export const D_SOCIETE2="Se conformer à une obligation légale"
export const D_SOCIETE3="Protéger et défendre les droits ou la propriété de l'entreprise"
export const D_SOCIETE5="Protéger la sécurité personnelle des Utilisateurs du Service ou du Publique"
export const D_SOCIETE4=" Prévenir ou enquêter sur d'éventuels actes répréhensibles en rapport avec le service"
export const D_SOCIETE6="Protéger contre la responsabilité légale"
export const SECURITE_DONNEE ="Sécurité de vos données personnelles"
export const SECURITE_DONNEE_DETAIL="La sécurité de vos données personnelles est importante pour nous, mais rappelez-vous qu'aucune méthode de transmission sur Internet, ni aucune méthode de le stockage électronique est 100% sécurisé. Alors que nous nous efforçons d'utiliser commercialement moyens acceptables pour protéger vos données personnelles, nous ne pouvons pas garantir sa sécurité absolue."
export const C_ENFANT="Confidentialité des enfants"
export const C_ENFANT_DETAIL="Notre service ne s'adresse à personne de moins de 13 ans. recueillir sciemment des informations personnellement identifiables de quiconque de moins de 13 ans. Si vous êtes parent ou tuteur et que vous savez que votre enfant nous a fourni des données personnelles, veuillez nous contacter. Si nous apprenons que nous avons collecté des données personnelles de quiconque de moins de 13 ans sans vérification du consentement parental, nous prenons étapes pour supprimer ces informations de nos serveurs."
export const C_ENFANT_DETAIL2="  Si nous devons nous fier au consentement comme base légale pour traiter votre informations et votre pays nécessite le consentement d'un parent, nous pouvons exiger le consentement de vos parents avant de collecter et d'utiliser informations."
export const LIENT_SITE=" Liens vers d'autres sites Web"
export const LIENT_SITE_DETAIL=" Notre service peut contenir des liens vers d'autres sites Web qui ne sont pas exploité par nous. Si vous cliquez sur un lien tiers, vous serez dirigé vers le site de ce tiers. Nous vous conseillons vivement de Consultez la politique de confidentialité de chaque site que vous visitez."
export const LIENT_SITE_DETAIL2=" Nous n'avons aucun contrôle et n'assumons aucune responsabilité pour le contenu, politiques de confidentialité ou pratiques de tout site tiers ou prestations de service."
export const M_POLITIQUE="Modifications de cette politique de confidentialité"
export const M_POLITIQUE_DETAIL=" Nous pouvons mettre à jour notre politique de confidentialité de temps à autre. Nous informerons Vous de tout changement en publiant la nouvelle politique de confidentialité sur cette page."
export const INFOS_CHANGE="Nous vous informerons par e-mail et / ou par un avis bien visible sur notre Service, avant que le changement ne devienne effectif et mettez à jour le Dernier mise à jour date en haut de cette politique de confidentialité."
export const INFOS_CHANGE_DETAIL="Il vous est conseillé de revoir cette politique de confidentialité périodiquement pour tout changements. Les modifications apportées à cette politique de confidentialité sont effectives lorsqu'elles sont publié sur cette page."
export const QUESTION_P=" Si vous avez des questions sur cette politique de confidentialité, vous pouvez contacter nous:"
export const PAR_M="par email: info@plaguifor.com"
export const PAR_TEL="par téléphone: +224 629-57-97-48"
export const P_CONFIDENTIEL="Politique de confidentialité pour PLAGUIFOR"
export const RSV="RSV"
export const PRESENTATEUR="PRESENTATEURS (TRICES):"
export const PARTICIPE_RECEV="Inscrivez-vous pour participer et recevoir une mise à jour par e-mail sur toute modification apportée à cette session."
export const CONDITION_INFOS="En soumettant mes informations, je consens à être contacté pour les termes et conditions décrits dans notre politique de confidentialité."

export const NIVEAU="Niveau :"
export const CONNECTEZ_VOUS="Connectez-vous sur la plateforme interne en tant que instrucrteur"
export const MONOTAIRE="GNF"
export const SESSION="Session du programme"
export const RENCONTRE_INSTRUCTEUR="RENCONTREZ LES INSTRUCTEURS"

export const INSCRIVEZ="Inscrivez-vous sur la plateforme interne"
export const INSCRIT_COURS="S'Inscrire"
export const ENREGISTRE="Enregistre"
export const CHECK="Incrivez vous pour recevoir des e-mails avec des conseils de création, même"
export const ANNUL="ANNULER"
export const CONNEXION="CONNEXION"
export const S_PROGRAM="Sélection d'un programme"
export const INS_FRAIS="Inscription et Frais"
export const NOUS_CONTACTE="Nous Contacter"
export const DEMANDE_INSCRIPTION="Demande d'inscription en"
export const A_COMPTE="Connexion"
export const R_MPASS="Réinitialiser le mot de passe"
export const DETAIL_R_MPASS ="Réinitialiser le mot de passe sur la plate-forme interne"
export const INSCRIT="S'inscrire en tant que instructeur"
export const AVIS="Abonner vous à notre newsletter:"
export const BONNE_CHANCE="BONNE CHANCE"
export const P_FORM="PLATEFORME"
export const G_G="GUINÉENNE DE FORMATIONS"
export const P_G="PLAGUIFOR CONAKRY, GUINÉE"
export const B_ADMIN=" BUREAUX ADMINISTRATIFS"
export const C_YEMBEYA="Carrefour Yembeya Commune De Ratoma"
export const BP="BP: 0000 Conakry"
export const PAYS="Guinée"
export const DESCRIPTION="Description"
export const Q_BASE ="QUALIFICATIONS DE BASE"
export const Q_APPRECIE="QUALIFICATIONS APPRÉCIÉES"
export const P_VOUS="PLAGUIFOR VOUS PERMET DE :"
export const POSEZ="Posez-nous vos questions avec :"
export const INFOS_AVIS="Soyez parmi les premiers à recevoir en temps opportun des informations sur les programmes et les événements, des conseils de carrière, les tendances de l'industrie et plus encore."

export const PARTENARIAT = "Il est par excellence, le fondement de nos actions et activités. Avec nous et à travers ce partenariat, vous avez accès et à portée des mains, une expertise académique et industrielle unique qui, assure et rassure d’une Organisation qualitative permettant à tout point de vue, de réaliser des bénéfices sur les dépenses couteuses liées au Développement, à la maintenance et à la fourniture de Programmes Educatifs. PLAGUIFOR s’engage à offrir plusieurs de ses programmes existants sur tout site de votre choix. C’est pourquoi, nous développons :"

export const CATEGORIE="Catégories"
export const FIN=" Fin"